project_id = "onhznjyccagjoefavbaq"

[functions.claim-camly]
verify_jwt = true

[functions.reset-reward]
verify_jwt = true

[functions.upload-r2]
verify_jwt = true

[functions.check-inactive-bans]
verify_jwt = false

[functions.check-content]
verify_jwt = false

[functions.fetch-bscscan-history]
verify_jwt = false

[functions.angel-chat]
verify_jwt = false

[functions.check-avatar]
verify_jwt = false

[functions.reset-all-rewards]
verify_jwt = true

[functions.send-merge-request]
verify_jwt = true

[functions.fun-profile-webhook]
verify_jwt = false

[functions.admin-get-conflicts]
verify_jwt = true

[functions.admin-resolve-conflict]
verify_jwt = true

[functions.admin-get-users-for-merge]
verify_jwt = true

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false
