project_id = "onhznjyccagjoefavbaq"

[functions.claim-camly]
verify_jwt = true

[functions.reset-reward]
verify_jwt = true

[functions.upload-r2]
verify_jwt = true

[functions.check-inactive-bans]
verify_jwt = false

[functions.check-content]
verify_jwt = false
